images:
  image:
    repository: ghcr.io/dispatcharr/dispatcharr
    tag: 0.20.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_17_image:
    repository: postgres
    tag: 17.9-bookworm
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  redis_image:
    repository: valkey/valkey
    tag: 9.0.3
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.9

consts:
  dispatcharr_container_name: dispatcharr
  celery_container_name: celery
  perms_container_name: permissions
  postgres_container_name: postgres
  redis_container_name: redis
  db_user: dispatcharr
  db_name: dispatcharr
