images:
  image:
    repository: vikunja/vikunja
    tag: 2.0.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: paradedb/paradedb
    tag: 0.21.9-pg18
  redis_image:
    repository: valkey/valkey
    tag: 9.0.3
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.9

consts:
  vikunja_container_name: vikunja
  perms_container_name: permissions
  postgres_container_name: postgres
  redis_container_name: redis
  data_path: /app/vikunja/files
  db_user: vikunja
  db_name: vikunja
