resources:
  limits:
    cpus: 2.0
    memory: 4096

openclaw:
  gateway_token: "test-token"
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  gateway_port:
    bind_mode: published
    port_number: 8085

ix_volumes:
  config: /opt/tests/mnt/openclaw/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
