{% set tpl = ix_lib.base.render.Render(values) %}

{% set fscrawler_net = tpl.networks.create_internal("fscrawler-net") %}

{% set c1 = tpl.add_container(values.consts.fscrawler_container_name, values.fscrawler.image_selector) %}
{% do c1.add_network(fscrawler_net) %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.consts.run_as_user, "gid": values.consts.run_as_group, "mode": "check"} %}

{% set es_config = {"password": values.fscrawler.elastic_password, "node_name": "fscrawler", "volume": values.storage.es_data} %}
{% set es = tpl.deps.elasticsearch(values.consts.elastic_search_container_name, "elastic_search_image", es_config, perm_container) %}
{% do es.container.add_network(fscrawler_net) %}

{% do c1.environment.add_env("FSCRAWLER_NAME", values.fscrawler.job_name) %}
{% do c1.environment.add_env("FSCRAWLER_FS_URL", values.consts.root_dir) %}
{% do c1.environment.add_env("FSCRAWLER_ELASTICSEARCH_URLS", es.get_url()) %}
{% do c1.environment.add_env("FSCRAWLER_ELASTICSEARCH_USERNAME", "elastic") %}
{% do c1.environment.add_env("FSCRAWLER_ELASTICSEARCH_PASSWORD", values.fscrawler.elastic_password) %}
{% do c1.environment.add_env("FSCRAWLER_REST_URL", "http://0.0.0.0:%d"|format(values.network.rest_port.port_number)) %}

{% do c1.set_user(values.consts.run_as_user, values.consts.run_as_group) %}
{% do c1.depends.add_dependency(values.consts.elastic_search_container_name, "service_healthy") %}
{% do c1.healthcheck.set_test("curl", {"port": values.network.rest_port.port_number}) %}
{% set cmd = namespace(x=[
  "--rest",
  "--loop", values.fscrawler.loop,
]) %}
{% if values.fscrawler.restart %}
  {% do cmd.x.append("--restart") %}
{% endif %}
{% do c1.set_command(cmd.x) %}

{% do c1.environment.add_user_envs(values.fscrawler.additional_envs) %}
{% do c1.add_port(values.network.rest_port) %}

{% do c1.add_storage(values.consts.root_dir, values.storage.root_dir) %}
{% do perm_container.add_or_skip_action("root-dir", values.storage.root_dir, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do es.container.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{{ tpl.render() | tojson }}
