{% set tpl = ix_lib.base.render.Render(values) %}

{% set dl_net = tpl.networks.create_internal("dl-net") %}

{% set c1 = tpl.add_container(values.consts.app_container_name, "image") %}
{% set cron = tpl.add_container(values.consts.cron_container_name, "cron_image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{# Postgres #}
{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.domain_locker.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(values.consts.postgres_container_name, values.domain_locker.postgres_image_selector, pg_config, perm_container) %}
{% do postgres.container.add_network(dl_net) %}

{% do c1.add_network(dl_net) %}
{% do c1.set_user(values.run_as.user, values.run_as.group) %}
{% do c1.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}
{% do c1.healthcheck.set_test("wget", {"port": values.network.web_port.port_number, "path": "/api/health"}) %}

{% do c1.environment.add_env("PORT", values.network.web_port.port_number) %}
{% do c1.environment.add_env("DL_ENV_TYPE", "selfHosted") %}
{% do c1.environment.add_env("DL_PG_HOST", values.consts.postgres_container_name) %}
{% do c1.environment.add_env("DL_PG_PORT", postgres.get_port()) %}
{% do c1.environment.add_env("DL_PG_NAME", values.consts.db_name) %}
{% do c1.environment.add_env("DL_PG_USER", values.consts.db_user) %}
{% do c1.environment.add_env("DL_PG_PASSWORD", values.domain_locker.db_password) %}
{% do c1.environment.add_user_envs(values.domain_locker.additional_envs) %}

{% do c1.add_port(values.network.web_port) %}

{% set crontasks = [
  "*/15 * * * * curl -f -X POST http://%s:%d/api/domain-monitor"|format(values.consts.app_container_name, values.network.web_port.port_number),
  "0 3 * * * curl -f -X POST http://%s:%d/api/domain-updater"|format(values.consts.app_container_name, values.network.web_port.port_number),
  "0 4 * * * curl -f -X POST http://%s:%d/api/expiration-reminders"|format(values.consts.app_container_name, values.network.web_port.port_number),
  "0 2 * * 0 curl -f -X POST http://%s:%d/api/cleanup-monitor-data"|format(values.consts.app_container_name, values.network.web_port.port_number),
] %}

{% do cron.add_network(dl_net) %}
{% do cron.set_user(values.run_as.user, values.run_as.group) %}
{% do cron.deploy.resources.set_profile("low") %}
{% do cron.depends.add_dependency(values.consts.app_container_name, "service_healthy") %}
{% do cron.environment.add_env("METRICS_PORT", 8080) %}
{% do cron.healthcheck.set_test("curl", {"port": 8080, "path": "/health"}) %}
{% do cron.configs.add("crontasks", crontasks | join("\n"), "/crontasks") %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
