images:
  image:
    repository: ghcr.io/editmysave/hyos/server
    tag: 0.0.20
  manager_image:
    repository: ghcr.io/editmysave/hyos/manager
    tag: 0.0.20
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  server_container_name: server
  manager_container_name: manager
  perms_container_name: permissions
  data_path: /data
