images:
  image:
    repository: dadoonet/fscrawler
    tag: 2.10-SNAPSHOT-ocr
  no_ocr_image:
    repository: dadoonet/fscrawler
    tag: 2.10-SNAPSHOT-noocr
  elastic_search_image:
    repository: elasticsearch
    tag: 9.3.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  fscrawler_container_name: fscrawler
  elastic_search_container_name: elastic-search
  perms_container_name: permissions
  root_dir: /crawler
  run_as_user: 10001
  run_as_group: 10001
