images:
  image:
    repository: ghcr.io/goauthentik/server
    tag: "2026.2.0"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_17_image:
    repository: postgres
    tag: 17.9-bookworm
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.9

consts:
  server_container_name: authentik-server
  worker_container_name: authentik-worker
  perms_container_name: permissions
  postgres_container_name: postgres
  db_user: authentik
  db_name: authentik
  data_base_path: /data
