resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: UTC

xmrig:
  use_remote_pool: false
  remote_pool_address: ""
  local_xmrig_port: 3333
  pool_username: ""
  pool_password: ""
  autodetect_algorithm: true
  algorithm: ""
  autodetect_coin: true
  coin: ""
  cpu_threads: 2
  cpu_priority: 1
  use_1gb_huge_pages: false
  use_msr_mod: false
  use_proxy: false
  use_arti_app_proxy: false
  arti_app_proxy_port: 9150
  proxy_host: ""
  proxy_port: 9150
  donate_percentage: 1

ix_volumes:
  config: /opt/tests/mnt/xmrig/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  additional_storage: []
