{% set tpl = ix_lib.base.render.Render(values) %}
{% set affine_net = tpl.networks.create_internal("affine-net") %}

{% set c1 = tpl.add_container(values.consts.affine_container_name, "image") %}
{% set migrations = tpl.add_container(values.consts.migrations_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.affine.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(values.consts.postgres_container_name, values.affine.postgres_image_selector, pg_config, perm_container) %}
{% do postgres.container.add_network(affine_net) %}

{% set redis_config = {
  "password": values.affine.redis_password,
  "volume": {"type": "temporary", "volume_config": {"volume_name": "redis-data"}},
} %}
{% set redis = tpl.deps.redis(values.consts.redis_container_name, "redis_image", redis_config, perm_container) %}
{% do redis.container.add_network(affine_net) %}

{% set containers = [c1, migrations] %}
{% for c in containers %}
  {% do c.add_network(affine_net) %}
  {% do c.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}
  {% do c.depends.add_dependency(values.consts.redis_container_name, "service_healthy") %}

  {% do c.environment.add_env("AFFINE_SERVER_PORT", values.network.web_port.port_number) %}
  {% do c.environment.add_env("REDIS_SERVER_HOST", values.consts.redis_container_name) %}
  {% do c.environment.add_env("REDIS_SERVER_PORT", redis.get_port()) %}
  {% do c.environment.add_env("REDIS_SERVER_PASSWORD", values.affine.redis_password) %}
  {% do c.environment.add_env("DATABASE_URL", postgres.get_url("postgresql")) %}

  {% do c.environment.add_user_envs(values.affine.additional_envs) %}

  {% do c.add_storage(values.consts.uploads_path, values.storage.uploads) %}
  {% do c.add_storage(values.consts.config_path, values.storage.config) %}
{% endfor %}

{# Migrations #}
{% do migrations.setup_as_helper(disable_network=false) %}
{% do migrations.set_command(['/bin/sh', '-c', 'node ./scripts/self-host-predeploy.js']) %}

{# Application #}
{% do c1.healthcheck.set_test("http", {"port": values.network.web_port.port_number, "path": "/info"}) %}
{% do c1.depends.add_dependency(values.consts.migrations_container_name, "service_completed_successfully") %}
{% do c1.add_port(values.network.web_port) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do redis.container.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
