images:
  image:
    repository: ghcr.io/viren070/aiostreams
    tag: v2.24.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  aiostreams_container_name: aiostreams
  perms_container_name: permissions
