annotations:
  min_scale_version: 24.10.2.2
app_version: v3.9.1
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/prometheus/prometheus/releases/
date_added: '2024-08-02'
description: The Prometheus monitoring system and time series database.
home: https://prometheus.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/prometheus/icons/icon.png
keywords:
- metrics
- prometheus
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: prometheus
run_as_context:
- description: Container [prometheus] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/prometheus/screenshots/screenshot1.png
sources:
- https://github.com/prometheus/prometheus
- https://prometheus.io
title: Prometheus
train: stable
version: 1.4.1
