resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: America/New_York

hytale:
  server_name: "Test Hytale Server"
  server_motd: "Welcome to the test server"
  server_password: ""
  max_players: 10
  default_gamemode: Adventure
  patchline: release
  auth_mode: ""
  whitelist: []
  skip_broken_mods: false
  max_view_radius: 32
  cookie_secure: false
  auto_update:
    enabled: true
    interval: 3600
    time: ""
    restart: true
    backup: true
  api:
    client_secret: "testpassword123"
    client_id: "hyos-manager"
  backup:
    enabled: true
    frequency: 60
    max_count: 10
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  game_port:
    bind_mode: published
    port_number: 8081
  api_port:
    bind_mode: published
    port_number: 8082
  manager_port:
    bind_mode: published
    port_number: 8083

ix_volumes:
  data: /opt/tests/mnt/hyos/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
