app_version: 2026.2.0
capabilities:
- description: ESPHome is able to use raw and packet sockets
  name: NET_RAW
- description: ESPHome is able to change user ID of processes
  name: SETUID
categories:
- home-automation
changelog_url: https://esphome.io/changelog/
date_added: '2025-01-24'
description: ESPHome is a system to control your microcontrollers by simple yet powerful
  configuration files and control them remotely through Home Automation systems.
home: https://esphome.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/esphome/icons/icon.svg
keywords:
- home-automation
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: esphome
run_as_context:
- description: Container [esphome] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/esphome/esphome
title: ESPHome
train: community
version: 1.2.2
