resources:
  limits:
    cpus: 2.0
    memory: 4096

seaweedfs:
  data_center_name: My Data Center
  rack_name: My Rack
  volume_size_limit_mb: 30000
  admin_user: admin
  admin_password: admin123
  master_peers: []
  additional_envs: []

network:
  admin_port:
    bind_mode: published
    port_number: 8000
  admin_grpc_port:
    bind_mode: published
    port_number: 8010

  worker_metrics_port:
    bind_mode: published
    port_number: 8084

  master_port:
    bind_mode: published
    port_number: 8080
  master_grpc_port:
    bind_mode: published
    port_number: 8089
  master_metrics_port:
    bind_mode: published
    port_number: 8086

  volume_port:
    bind_mode: published
    port_number: 8081
  volume_grpc_port:
    bind_mode: published
    port_number: 8090
  volume_metrics_port:
    bind_mode: published
    port_number: 8085

  filer_port:
    bind_mode: published
    port_number: 8082
  filer_grpc_port:
    bind_mode: published
    port_number: 8091
  filer_metrics_port:
    bind_mode: published
    port_number: 8087

  s3_port:
    bind_mode: published
    port_number: 8083
    certificate_id: null
  s3_grpc_port:
    bind_mode: published
    port_number: 8092
  s3_metrics_port:
    bind_mode: published
    port_number: 8088

run_as:
  user: 568
  group: 568

ix_volumes:
  filer_data: /opt/tests/mnt/seaweedfs/filer-data
  volume_data: /opt/tests/mnt/seaweedfs/volume-data
  master_data: /opt/tests/mnt/seaweedfs/master-data
  admin_data: /opt/tests/mnt/seaweedfs/admin-data
  worker_data: /opt/tests/mnt/seaweedfs/worker-data

storage:
  filer_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: filer_data
      create_host_path: true
  volume_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: volume_data
      create_host_path: true
  master_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: master_data
      create_host_path: true
  admin_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: admin_data
      create_host_path: true
  worker_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: worker_data
      create_host_path: true
  additional_storage: []
