annotations:
  min_scale_version: 24.10.2.2
app_version: 12.3.3
capabilities: []
categories:
- productivity
changelog_url: https://grafana.com/docs/grafana/latest/whatsnew/
date_added: '2024-08-01'
description: Grafana is the open source analytics & monitoring solution for every
  database.
home: https://grafana.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/grafana/icons/icon.png
keywords:
- analytics
- monitoring
- metrics
- dashboards
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: grafana
run_as_context:
- description: Container [grafana] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/grafana/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/grafana/screenshots/screenshot2.png
sources:
- https://hub.docker.com/r/grafana/grafana
- https://github.com/grafana
title: Grafana
train: community
version: 1.4.2
