{% set tpl = ix_lib.base.render.Render(values) %}

{% set briefkasten_net = tpl.networks.create_internal("briefkasten-net") %}
{% if values.briefkasten.postgres_image_selector == "postgres_15_image" %}
  {% do tpl.notes.add_deprecation("Postgres 15 is deprecated and will be removed in the near future. Please upgrade.") %}
{% endif %}

{% set c1 = tpl.add_container(values.consts.briefkasten_container_name, "image") %}
{% set init = tpl.add_container(values.consts.init_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.consts.run_user, "gid": values.consts.run_group, "mode": "check"} %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.briefkasten.postgres_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(values.consts.pg_container_name, values.briefkasten.postgres_image_selector, pg_config, perm_container) %}
{% do postgres.container.add_network(briefkasten_net) %}

{% set containers = [c1, init] %}
{% for c in containers %}
  {% do c.add_network(briefkasten_net) %}
  {% do c.set_user(values.consts.run_user, values.consts.run_group) %}

  {% do c.depends.add_dependency(values.consts.pg_container_name, "service_healthy") %}

  {% do c.environment.add_env("PORT", values.network.web_port.port_number) %}
  {% do c.environment.add_env("NODE_ENV", "production") %}
  {% do c.environment.add_env("DATABASE_URL", postgres.get_url("postgres")) %}
  {% do c.environment.add_env("NEXTAUTH_SECRET", values.briefkasten.nextauth_secret) %}
  {% do c.environment.add_env("NEXTAUTH_URL", values.briefkasten.nextauth_url) %}
  {% do c.environment.add_env("NEXTAUTH_URL_INTERNAL", "http://127.0.0.1:%d"|format(values.network.web_port.port_number)) %}

  {% if values.briefkasten.smtp.enabled %}
    {% do c.environment.add_env("SMTP_HOST", values.briefkasten.smtp.server) %}
    {% do c.environment.add_env("SMTP_FROM", values.briefkasten.smtp.from) %}
  {% endif %}

  {% if values.briefkasten.github.enabled %}
    {% do c.environment.add_env("GITHUB_ID", values.briefkasten.github.id) %}
    {% do c.environment.add_env("GITHUB_SECRET", values.briefkasten.github.secret) %}
  {% endif %}

  {% if values.briefkasten.google.enabled %}
    {% do c.environment.add_env("GOOGLE_ID", values.briefkasten.google.id) %}
    {% do c.environment.add_env("GOOGLE_SECRET", values.briefkasten.google.secret) %}
  {% endif %}

  {% if values.briefkasten.keycloak.enabled %}
    {% do c.environment.add_env("KEYCLOAK_NAME", values.briefkasten.keycloak.name) %}
    {% do c.environment.add_env("KEYCLOAK_ID", values.briefkasten.keycloak.id) %}
    {% do c.environment.add_env("KEYCLOAK_SECRET", values.briefkasten.keycloak.secret) %}
    {% do c.environment.add_env("KEYCLOAK_ISSUER", values.briefkasten.keycloak.issuer) %}
  {% endif %}

  {% if values.briefkasten.authentik.enabled %}
    {% do c.environment.add_env("AUTHENTIK_NAME", values.briefkasten.authentik.name) %}
    {% do c.environment.add_env("AUTHENTIK_ID", values.briefkasten.authentik.id) %}
    {% do c.environment.add_env("AUTHENTIK_SECRET", values.briefkasten.authentik.secret) %}
    {% do c.environment.add_env("AUTHENTIK_ISSUER", values.briefkasten.authentik.issuer) %}
  {% endif %}

  {% do c.environment.add_user_envs(values.briefkasten.additional_envs) %}

  {% for store in values.storage.additional_storage %}
    {% do c.add_storage(store.mount_path, store) %}
  {% endfor %}
{% endfor %}

{% for store in values.storage.additional_storage %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% do init.setup_as_helper(disable_network=false) %}
{% do init.set_entrypoint(["/bin/sh", "-c"]) %}
{% do init.set_command([
  "echo 'Migrating database...'\n"
  "pnpm db:push || (echo 'DB migration failed...' && exit 1)\n"
  "echo 'Database migration complete. Application will now start'\n"
]) %}

{% do c1.depends.add_dependency(values.consts.init_container_name, "service_completed_successfully") %}
{% do c1.healthcheck.set_test("tcp", {"port": values.network.web_port.port_number}) %}

{% do c1.add_port(values.network.web_port) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% for c in containers %}
    {% do c.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% endfor %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
