{% set tpl = ix_lib.base.render.Render(values) %}

{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% set c1 = tpl.add_container(values.consts.openclaw_container_name, "image") %}
{% do c1.set_user(values.run_as.user, values.run_as.group) %}
{% do c1.set_init(true) %}

{% do c1.healthcheck.set_test("curl", {"port": values.network.gateway_port.port_number, "path": "/healthz"}) %}

{% do c1.set_command([
  "node", "openclaw.mjs",
  "gateway", "--allow-unconfigured",
  "--bind", "lan",
  "--port", values.network.gateway_port.port_number,
]) %}

{% do c1.environment.add_env("HOME", values.consts.home_dir) %}
{% do c1.environment.add_env("NODE_ENV", "production") %}
{% do c1.environment.add_env("OPENCLAW_GATEWAY_TOKEN", values.openclaw.gateway_token) %}

{% do c1.environment.add_user_envs(values.openclaw.additional_envs) %}

{% do c1.add_port(values.network.gateway_port) %}

{% do c1.add_storage(values.consts.home_dir, values.storage.config) %}
{% do perm_container.add_or_skip_action("config", values.storage.config, perms_config) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.gateway_port) %}

{{ tpl.render() | tojson }}
