images:
  image:
    repository: ghcr.io/dgtlmoon/changedetection.io
    tag: 0.53.5
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  change_detection_container_name: change-detection
  perms_container_name: permissions
