resources:
  limits:
    cpus: 2
    memory: 2048

domain_locker:
  postgres_image_selector: postgres_18_image
  db_password: testpassword123
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 30120

ix_volumes:
  postgres_data: /opt/tests/domain-locker/postgres_data

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
