images:
  image:
    repository: postgres
    tag: 17.9-bookworm
  v17_pgvector_image:
    repository: pgvector/pgvector
    tag: 0.8.1-pg17
  v15_pgvector_image:
    repository: pgvector/pgvector
    tag: 0.8.1-pg15
  v15_image:
    repository: postgres
    tag: 15.17-bookworm
  v16_image:
    repository: postgres
    tag: 16.13-bookworm
  v16_pgvector_image:
    repository: pgvector/pgvector
    tag: 0.8.1-pg16
  v18_image:
    repository: postgres
    tag: 18.3-trixie
  v18_pgvector_image:
    repository: pgvector/pgvector
    tag: 0.8.2-pg18-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.9
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  postgres_container_name: postgres
  perms_container_name: permissions
