resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

fscrawler:
  image_selector: image
  elastic_password: changeme
  job_name: my_job
  restart: true
  loop: 2
  additional_envs: []
network:
  host_network: false
  rest_port:
    bind_mode: "published"
    port_number: 8085

ix_volumes:
  es_data: /opt/tests/mnt/fscrawler/es_data
  root_dir: /opt/tests/mnt/fscrawler/root_dir

storage:
  es_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: es_data
      create_host_path: true
  root_dir:
    type: ix_volume
    read_only: true
    ix_volume_config:
      dataset_name: root_dir
      create_host_path: true
  additional_storage: []
