images:
  image:
    repository: lissy93/domain-locker
    tag: 0.1.4
  cron_image:
    repository: ixsystems/cron
    tag: 1.0.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.9

consts:
  app_container_name: domain-locker
  postgres_container_name: postgres
  cron_container_name: cron
  perms_container_name: permissions
  db_name: domain_locker
  db_user: domain_locker
