images:
  image:
    repository: ghcr.io/seerr-team/seerr
    tag: v3.0.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  perms_container_name: permissions
  seerr_container_name: seerr
