{% set tpl = ix_lib.base.render.Render(values) %}

{% set ma_net = tpl.networks.create_internal("mail-archiver-net") %}

{% set c1 = tpl.add_container(values.consts.mail_archiver_container_name, "image") %}
{% do c1.add_network(ma_net) %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.mail_archiver.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(values.consts.postgres_container_name, values.mail_archiver.postgres_image_selector, pg_config, perm_container) %}
{% do postgres.container.add_network(ma_net) %}

{% do c1.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}
{% do c1.healthcheck.set_test("http", {"port": values.network.web_port.port_number, "path": "/favicon.svg"}) %}

{% do c1.environment.add_env("Kestrel__Endpoints__Http__Url", "http://*:%s/"|format(values.network.web_port.port_number)) %}
{% do c1.environment.add_env("Authentication__Username", values.mail_archiver.admin_username) %}
{% do c1.environment.add_env("Authentication__Password", values.mail_archiver.admin_password) %}
{% do c1.environment.add_env("TimeZone__DisplayTimeZoneId", values.TZ) %}
{% do c1.environment.add_env("ConnectionStrings__DefaultConnection", postgres.get_url("dotnet_pgsql")) %}

{% do c1.environment.add_user_envs(values.mail_archiver.additional_envs) %}
{% do c1.add_storage("/app/DataProtection-Keys", values.storage.data) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% do c1.add_port(values.network.web_port) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
