resources:
  limits:
    cpus: 2.0
    memory: 4096

code_server:
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  homedir: /opt/tests/mnt/code-server/homedir

storage:
  use_deprecated_volumes: false
  homedir:
    type: ix_volume
    ix_volume_config:
      dataset_name: homedir
      create_host_path: true
  additional_storage: []
